
import React from 'react';
import { Link } from 'react-router-dom';
import { allTextTools } from '@/data/textToolsData';

interface MegaMenuProps {
  activeCategory: string | null;
  onClose: () => void;
}

const MegaMenu: React.FC<MegaMenuProps> = ({ activeCategory, onClose }) => {
  const toolCategories = {
    text: {
      title: 'Text Tools',
      tools: [
        { name: 'Case Converter', path: '/tools/text/CaseConverter' },
        { name: 'Sentence Case Converter', path: '/tools/text/SentenceCaseConverter' },
        { name: 'Binary ⇄ Text Converter', path: '/tools/text/BinaryTextConverter' },
        { name: 'Text to Hex Converter', path: '/tools/text/TextToHexConverter' },
        { name: 'Hex to Text Converter', path: '/tools/text/HexToTextConverter' },
        { name: 'Text to ASCII', path: '/tools/text/TextToAsciiConverter' },
        { name: 'ASCII to Text', path: '/tools/text/AsciiToTextConverter' },
        { name: 'Reverse Text Generator', path: '/tools/text/ReverseTextGenerator' },
        { name: 'Text to Speech Converter', path: '/tools/text/TextToSpeechConverter' },
        { name: 'Unicode Character Converter', path: '/tools/text/UnicodeCharacterConverter' },
        { name: 'Number to Words Converter', path: '/tools/text/NumberToWordsConverter' },
        { name: 'Random Password Generator', path: '/tools/text/RandomPasswordGenerator' },
        { name: 'Advanced Lorem Ipsum', path: '/tools/text/LoremIpsumGenerator' },
        { name: 'Advanced Slug Generator', path: '/tools/text/SlugGenerator' },
        { name: 'Random Word Generator', path: '/tools/text/RandomWordGenerator' },
        { name: 'Random Letter Generator', path: '/tools/text/RandomLetterGenerator' },
        { name: 'Text Repeater', path: '/tools/text/TextRepeater' },
        { name: 'Hashtag Generator', path: '/tools/text/HashtagGenerator' },
        { name: 'Blog Title Generator', path: '/tools/text/BlogTitleGenerator' },
        { name: 'Strong Password Generator', path: '/tools/text/StrongPasswordGenerator' },
        { name: 'Article Title Generator', path: '/tools/text/ArticleTitleGenerator' },
        { name: 'Username Generator', path: '/tools/text/UsernameGenerator' },
        { name: 'Business Name Generator', path: '/tools/text/BusinessNameGenerator' },
        { name: 'Online Word Counter', path: '/tools/text/WordCounter' },
        { name: 'Character Counter', path: '/tools/text/CharacterCounter' },
        { name: 'Duplicate Line Remover', path: '/tools/text/DuplicateLineRemover' },
        { name: 'Advanced Whitespace Remover', path: '/tools/text/WhitespaceRemover' },
        { name: 'Text Compare (Diff Checker)', path: '/tools/text/TextCompare' },
        { name: 'Find and Replace Text', path: '/tools/text/FindAndReplaceText' },
        { name: 'Keyword Density Checker', path: '/tools/text/KeywordDensityChecker' },
        { name: 'Meta Description Generator', path: '/tools/text/MetaDescriptionGenerator' },
        { name: 'Text Summarizer', path: '/tools/text/TextSummarizer' },
        { name: 'Plagiarism Checker (Basic)', path: '/tools/text/PlagiarismChecker' },
        { name: 'Reading Time Calculator', path: '/tools/text/ReadingTimeCalculator' },
        { name: 'Language Detector', path: '/tools/text/LanguageDetector' },
        { name: 'Bold Text Generator', path: '/tools/text/BoldTextGenerator' },
        { name: 'Italic Text Generator', path: '/tools/text/ItalicTextGenerator' },
        { name: 'Fancy Text Generator', path: '/tools/text/FancyTextGenerator' },
        { name: 'Zalgo Glitch Text', path: '/tools/text/ZalgoGlitchText' },
        { name: 'Big Text (ASCII) Generator', path: '/tools/text/BigTextGenerator' },
        { name: 'Advanced ASCII Art Generator', path: '/tools/text/AsciiArtGenerator' },
        { name: 'Yoda Translator', path: '/tools/text/YodaTranslator' },
        { name: 'Morse Code Translator', path: '/tools/text/MorseCodeTranslator' },
        { name: 'Emoji Text Generator', path: '/tools/text/EmojiTextGenerator' },
        { name: 'Text Art Generator', path: '/tools/text/TextArtGenerator' },
        { name: 'Upside Down Text Generator', path: '/tools/text/UpsideDownTextGenerator' },
      ]
    },
    web: {
      title: 'Web Tools',
      tools: [
        { name: 'HTML Previewer', path: '/tools/web/HtmlPreviewer' },
        { name: 'HTML Validator', path: '/tools/web/HtmlValidator' },
        { name: 'CSS Validator', path: '/tools/web/CssValidator' },
        { name: 'JavaScript Minifier', path: '/tools/web/JavaScriptMinifier' },
        { name: 'CSS Minifier', path: '/tools/web/CssMinifier' },
        { name: 'HTML Minifier', path: '/tools/web/HtmlMinifier' },
        { name: 'JSON Formatter', path: '/tools/web/JsonFormatter' },
        { name: 'XML Formatter', path: '/tools/web/XmlFormatter' },
        { name: 'Base64 Encoder/Decoder', path: '/tools/web/Base64EncoderDecoder' },
        { name: 'URL Encoder/Decoder', path: '/tools/web/UrlEncoderDecoder' },
        { name: 'HTML Entity Encoder', path: '/tools/web/HtmlEntityEncoder' },
        { name: 'Regex Tester', path: '/tools/web/RegexTester' },
        { name: 'SEO Meta Tag Generator', path: '/tools/web/SeoMetaTagGenerator' },
        { name: 'Open Graph Generator', path: '/tools/web/OpenGraphGenerator' },
        { name: 'Twitter Card Generator', path: '/tools/web/TwitterCardGenerator' },
        { name: 'Robots.txt Generator', path: '/tools/web/RobotsTxtGenerator' },
        { name: 'Sitemap Generator', path: '/tools/web/SitemapGenerator' },
        { name: 'Schema Markup Generator', path: '/tools/web/SchemaMarkupGenerator' },
        { name: 'Keyword Density Analyzer', path: '/tools/web/KeywordDensityAnalyzer' },
        { name: 'Page Speed Analyzer', path: '/tools/web/PageSpeedAnalyzer' },
        { name: 'Broken Link Checker', path: '/tools/web/BrokenLinkChecker' },
        { name: 'SERP Preview Tool', path: '/tools/web/SerpPreviewTool' },
        { name: 'Color Palette Generator', path: '/tools/web/ColorPaletteGenerator' },
        { name: 'Gradient Generator', path: '/tools/web/GradientGenerator' },
        { name: 'Box Shadow Generator', path: '/tools/web/BoxShadowGenerator' },
        { name: 'Border Radius Generator', path: '/tools/web/BorderRadiusGenerator' },
        { name: 'CSS Grid Generator', path: '/tools/web/CssGridGenerator' },
        { name: 'Flexbox Generator', path: '/tools/web/FlexboxGenerator' },
        { name: 'Font Pairing Tool', path: '/tools/web/FontPairingTool' },
        { name: 'Favicon Generator', path: '/tools/web/FaviconGenerator' },
        { name: 'CSS Animation Generator', path: '/tools/web/CssAnimationGenerator' },
        { name: 'QR Code Generator', path: '/tools/web/QrCodeGenerator' },
        { name: 'SSL Certificate Checker', path: '/tools/web/SslCertificateChecker' },
        { name: 'Website Security Scanner', path: '/tools/web/WebsiteSecurityScanner' },
        { name: 'HTTP Header Checker', path: '/tools/web/HttpHeaderChecker' },
        { name: 'WHOIS Lookup', path: '/tools/web/WhoisLookup' },
        { name: 'DNS Lookup Tool', path: '/tools/web/DnsLookupTool' },
        { name: 'IP Address Lookup', path: '/tools/web/IpAddressLookup' },
        { name: 'Port Scanner', path: '/tools/web/PortScanner' },
        { name: 'Website Uptime Monitor', path: '/tools/web/WebsiteUptimeMonitor' },
        { name: 'Ping Test Tool', path: '/tools/web/PingTestTool' },
      ]
    },
    image: {
      title: 'Image Tools',
      tools: [
        { name: 'JPEG to PNG Converter', path: '/tools/image/JpegToPngConverter' },
        { name: 'PNG to JPEG Converter', path: '/tools/image/PngToJpegConverter' },
        { name: 'WebP Converter', path: '/tools/image/WebpConverter' },
        { name: 'GIF to MP4 Converter', path: '/tools/image/GifToMp4Converter' },
        { name: 'SVG to PNG Converter', path: '/tools/image/SvgToPngConverter' },
        { name: 'HEIC to JPEG Converter', path: '/tools/image/HeicToJpegConverter' },
        { name: 'RAW Image Converter', path: '/tools/image/RawImageConverter' },
        { name: 'Batch Image Converter', path: '/tools/image/BatchImageConverter' },
        { name: 'ICO to PNG Converter', path: '/tools/image/IcoToPngConverter' },
        { name: 'TIFF to PDF Converter', path: '/tools/image/TiffToPdfConverter' },
        { name: 'Image Resizer', path: '/tools/image/ImageResizer' },
        { name: 'Image Cropper', path: '/tools/image/ImageCropper' },
        { name: 'Image Rotator', path: '/tools/image/ImageRotator' },
        { name: 'Background Remover', path: '/tools/image/BackgroundRemover' },
        { name: 'Image Filters', path: '/tools/image/ImageFilters' },
        { name: 'Brightness Adjuster', path: '/tools/image/BrightnessAdjuster' },
        { name: 'Color Adjuster', path: '/tools/image/ColorAdjuster' },
        { name: 'Image Blur Tool', path: '/tools/image/ImageBlurTool' },
        { name: 'Image Sharpener', path: '/tools/image/ImageSharpener' },
        { name: 'Watermark Adder', path: '/tools/image/WatermarkAdder' },
        { name: 'Image Compressor', path: '/tools/image/ImageCompressor' },
        { name: 'Lossless Compressor', path: '/tools/image/LosslessCompressor' },
        { name: 'JPEG Optimizer', path: '/tools/image/JpegOptimizer' },
        { name: 'PNG Optimizer', path: '/tools/image/PngOptimizer' },
        { name: 'Image Metadata Remover', path: '/tools/image/ImageMetadataRemover' },
        { name: 'Batch Compressor', path: '/tools/image/BatchCompressor' },
        { name: 'Progressive JPEG Creator', path: '/tools/image/ProgressiveJpegCreator' },
        { name: 'Image Size Analyzer', path: '/tools/image/ImageSizeAnalyzer' },
        { name: 'Placeholder Image Generator', path: '/tools/image/PlaceholderImageGenerator' },
        { name: 'QR Code to Image', path: '/tools/image/QrCodeToImage' },
        { name: 'Gradient Image Generator', path: '/tools/image/GradientImageGenerator' },
        { name: 'Color Palette Extractor', path: '/tools/image/ColorPaletteExtractor' },
        { name: 'Noise Pattern Generator', path: '/tools/image/NoisePatternGenerator' },
        { name: 'Avatar Generator', path: '/tools/image/AvatarGenerator' },
        { name: 'Favicon Generator', path: '/tools/image/FaviconGenerator' },
        { name: 'Social Media Image Generator', path: '/tools/image/SocialMediaImageGenerator' },
      ]
    },
    calculators: {
      title: 'Calculators',
      tools: [
        { name: 'Basic Calculator', path: '/tools/calculators/BasicCalculator' },
        { name: 'Scientific Calculator', path: '/tools/calculators/ScientificCalculator' },
        { name: 'Fraction Calculator', path: '/tools/calculators/FractionCalculator' },
        { name: 'Percentage Calculator', path: '/tools/calculators/PercentageCalculator' },
        { name: 'Square Root Calculator', path: '/tools/calculators/SquareRootCalculator' },
        { name: 'Algebra Calculator', path: '/tools/calculators/AlgebraCalculator' },
        { name: 'Binary Calculator', path: '/tools/calculators/BinaryCalculator' },
        { name: 'Matrix Calculator', path: '/tools/calculators/MatrixCalculator' },
        { name: 'Loan Calculator', path: '/tools/calculators/LoanCalculator' },
        { name: 'Mortgage Calculator', path: '/tools/calculators/MortgageCalculator' },
        { name: 'Investment Calculator', path: '/tools/calculators/InvestmentCalculator' },
        { name: 'Retirement Calculator', path: '/tools/calculators/RetirementCalculator' },
        { name: 'Tax Calculator', path: '/tools/calculators/TaxCalculator' },
        { name: 'Salary Calculator', path: '/tools/calculators/SalaryCalculator' },
        { name: 'Budget Calculator', path: '/tools/calculators/BudgetCalculator' },
        { name: 'ROI Calculator', path: '/tools/calculators/ROICalculator' },
        { name: 'Currency Converter', path: '/tools/calculators/CurrencyConverter' },
        { name: 'Tip Calculator', path: '/tools/calculators/TipCalculator' },
        { name: 'Unit Converter', path: '/tools/calculators/UnitConverter' },
        { name: 'Temperature Converter', path: '/tools/calculators/TemperatureConverter' },
        { name: 'Length Converter', path: '/tools/calculators/LengthConverter' },
        { name: 'Weight Converter', path: '/tools/calculators/WeightConverter' },
        { name: 'Volume Converter', path: '/tools/calculators/VolumeConverter' },
        { name: 'Area Calculator', path: '/tools/calculators/AreaCalculator' },
        { name: 'Speed Converter', path: '/tools/calculators/SpeedConverter' },
        { name: 'Time Zone Converter', path: '/tools/calculators/TimeZoneConverter' },
        { name: 'Date Calculator', path: '/tools/calculators/DateCalculator' },
        { name: 'Age Calculator', path: '/tools/calculators/AgeCalculator' },
        { name: 'BMI Calculator', path: '/tools/calculators/BMICalculator' },
        { name: 'Calorie Calculator', path: '/tools/calculators/CalorieCalculator' },
        { name: 'GPA Calculator', path: '/tools/calculators/GPACalculator' },
        { name: 'Fuel Cost Calculator', path: '/tools/calculators/FuelCostCalculator' },
        { name: 'Paint Calculator', path: '/tools/calculators/PaintCalculator' },
        { name: 'Pregnancy Calculator', path: '/tools/calculators/PregnancyCalculator' },
      ]
    },
    productivity: {
      title: 'Productivity',
      tools: [
        { name: 'Advanced Todo List', path: '/tools/productivity/advanced-todo-list' },
        { name: 'Kanban Board', path: '/tools/productivity/kanban-board' },
        { name: 'Project Planner', path: '/tools/productivity/project-planner' },
        { name: 'Team Task Manager', path: '/tools/productivity/team-task-manager' },
        { name: 'Goal Tracker', path: '/tools/productivity/goal-tracker' },
        { name: 'Habit Tracker', path: '/tools/productivity/habit-tracker' },
        { name: 'Priority Matrix', path: '/tools/productivity/priority-matrix' },
        { name: 'Milestone Tracker', path: '/tools/productivity/milestone-tracker' },
        { name: 'Time Tracker', path: '/tools/productivity/time-tracker' },
        { name: 'Pomodoro Timer', path: '/tools/productivity/pomodoro-timer' },
        { name: 'Work Schedule Planner', path: '/tools/productivity/work-schedule-planner' },
        { name: 'Meeting Scheduler', path: '/tools/productivity/meeting-scheduler' },
        { name: 'Time Zone Planner', path: '/tools/productivity/time-zone-planner' },
        { name: 'Calendar Sync Tool', path: '/tools/productivity/calendar-sync-tool' },
        { name: 'Deadline Calculator', path: '/tools/productivity/deadline-calculator' },
        { name: 'Time Blocking Tool', path: '/tools/productivity/time-blocking-tool' },
        { name: 'Digital Note System', path: '/tools/productivity/digital-note-system' },
        { name: 'Document Organizer', path: '/tools/productivity/document-organizer' },
        { name: 'Contact Manager', path: '/tools/productivity/contact-manager' },
        { name: 'Bookmark Manager', path: '/tools/productivity/bookmark-manager' },
        { name: 'Password Organizer', path: '/tools/productivity/password-organizer' },
        { name: 'File Naming System', path: '/tools/productivity/file-naming-system' },
        { name: 'Digital Workspace', path: '/tools/productivity/digital-workspace' },
        { name: 'Archive System', path: '/tools/productivity/archive-system' },
        { name: 'Team Collaboration Hub', path: '/tools/productivity/team-collaboration-hub' },
        { name: 'Shared Workspace', path: '/tools/productivity/shared-workspace' },
        { name: 'Meeting Notes Organizer', path: '/tools/productivity/meeting-notes-organizer' },
        { name: 'Team Calendar', path: '/tools/productivity/team-calendar' },
        { name: 'Project Dashboard', path: '/tools/productivity/project-dashboard' },
        { name: 'Resource Sharing Tool', path: '/tools/productivity/resource-sharing-tool' },
        { name: 'Feedback Collection', path: '/tools/productivity/feedback-collection' },
        { name: 'Team Communication', path: '/tools/productivity/team-communication' },
      ]
    },
    archive: {
      title: 'Archive Tools',
      tools: [
        { name: 'ZIP Archive Creator', path: '/tools/archive/zip-creator' },
        { name: 'ZIP File Extractor', path: '/tools/archive/zip-extractor' },
        { name: 'RAR File Extractor', path: '/tools/archive/rar-extractor' },
        { name: '7-Zip Creator', path: '/tools/archive/7z-creator' },
        { name: 'TAR Archive Tool', path: '/tools/archive/tar-tool' },
        { name: 'GZIP Compressor', path: '/tools/archive/gzip-compressor' },
        { name: 'Multi-format Extractor', path: '/tools/archive/multi-extractor' },
        { name: 'Batch Archive Creator', path: '/tools/archive/batch-creator' },
        { name: 'Archive Format Converter', path: '/tools/archive/format-converter' },
        { name: 'ZIP to RAR Converter', path: '/tools/archive/zip-to-rar' },
        { name: 'RAR to ZIP Converter', path: '/tools/archive/rar-to-zip' },
        { name: '7Z to ZIP Converter', path: '/tools/archive/7z-to-zip' },
        { name: 'TAR to ZIP Converter', path: '/tools/archive/tar-to-zip' },
        { name: 'ISO File Extractor', path: '/tools/archive/iso-extractor' },
        { name: 'CAB File Extractor', path: '/tools/archive/cab-extractor' },
        { name: 'DMG File Extractor', path: '/tools/archive/dmg-extractor' },
        { name: 'Archive Inspector', path: '/tools/archive/archive-inspector' },
        { name: 'File Size Analyzer', path: '/tools/archive/size-analyzer' },
        { name: 'Duplicate File Finder', path: '/tools/archive/duplicate-finder' },
        { name: 'Archive Repair Tool', path: '/tools/archive/repair-tool' },
        { name: 'Password Recovery', path: '/tools/archive/password-recovery' },
        { name: 'Archive Splitter', path: '/tools/archive/splitter' },
        { name: 'Archive Merger', path: '/tools/archive/merger' },
        { name: 'Compression Analyzer', path: '/tools/archive/compression-analyzer' },
        { name: 'File Compressor', path: '/tools/archive/file-compressor' },
        { name: 'Archive Converter', path: '/tools/archive/archive-converter' },
        { name: 'Backup Archive Creator', path: '/tools/archive/backup-creator' },
        { name: 'Incremental Backup Tool', path: '/tools/archive/incremental-backup' },
        { name: 'Backup Restoration Tool', path: '/tools/archive/backup-restore' },
        { name: 'Backup Verification', path: '/tools/archive/backup-verify' },
        { name: 'Backup Scheduler', path: '/tools/archive/backup-scheduler' },
        { name: 'Cloud Backup Sync', path: '/tools/archive/cloud-sync' },
        { name: 'Backup Catalog', path: '/tools/archive/backup-catalog' },
        { name: 'Backup Encryption', path: '/tools/archive/backup-encryption' },
      ]
    },
    security: {
      title: 'Security',
      tools: [
        { name: 'Strong Password Generator', path: '/tools/security/strong-password-generator' },
        { name: 'Passphrase Generator', path: '/tools/security/passphrase-generator' },
        { name: 'Password Strength Analyzer', path: '/tools/security/password-strength-analyzer' },
        { name: 'Password Breach Checker', path: '/tools/security/password-breach-checker' },
        { name: 'Bulk Password Generator', path: '/tools/security/bulk-password-generator' },
        { name: 'Password Policy Generator', path: '/tools/security/password-policy-generator' },
        { name: 'PIN Code Generator', path: '/tools/security/pin-code-generator' },
        { name: 'Recovery Key Generator', path: '/tools/security/recovery-key-generator' },
        { name: 'Text Encryption Tool', path: '/tools/security/text-encryption-tool' },
        { name: 'File Encryption Tool', path: '/tools/security/file-encryption-tool' },
        { name: 'Base64 Encoder/Decoder', path: '/tools/security/base64-encoder-decoder' },
        { name: 'Caesar Cipher Tool', path: '/tools/security/caesar-cipher-tool' },
        { name: 'ROT13 Encoder', path: '/tools/security/rot13-encoder' },
        { name: 'Hash Generator', path: '/tools/security/hash-generator' },
        { name: 'HMAC Generator', path: '/tools/security/hmac-generator' },
        { name: 'Digital Signature Tool', path: '/tools/security/digital-signature-tool' },
        { name: 'Privacy Scanner', path: '/tools/security/privacy-scanner' },
        { name: 'Metadata Remover', path: '/tools/security/metadata-remover' },
        { name: 'Anonymous URL Generator', path: '/tools/security/anonymous-url-generator' },
        { name: 'Secure File Shredder', path: '/tools/security/secure-file-shredder' },
        { name: 'IP Address Lookup', path: '/tools/security/ip-address-lookup' },
        { name: 'VPN Connection Tester', path: '/tools/security/vpn-connection-tester' },
        { name: 'Cookie Analyzer', path: '/tools/security/cookie-analyzer' },
        { name: 'Browser Fingerprint Test', path: '/tools/security/browser-fingerprint-test' },
        { name: 'Security Audit Dashboard', path: '/tools/security/security-audit-dashboard' },
        { name: 'Website Security Scanner', path: '/tools/security/website-security-scanner' },
        { name: 'SSL Certificate Checker', path: '/tools/security/ssl-certificate-checker' },
        { name: 'Port Security Scanner', path: '/tools/security/port-security-scanner' },
        { name: 'Email Security Checker', path: '/tools/security/email-security-checker' },
        { name: 'Two-Factor Auth Setup', path: '/tools/security/two-factor-auth-setup' },
        { name: 'Security Checklist', path: '/tools/security/security-checklist' },
        { name: 'Vulnerability Database', path: '/tools/security/vulnerability-database' },
      ]
    },
    video: {
      title: 'Video Tools',
      tools: [
        { name: 'MP4 Video Converter', path: '/tools/video/mp4-video-converter' },
        { name: 'AVI Video Converter', path: '/tools/video/avi-video-converter' },
        { name: 'MOV Video Converter', path: '/tools/video/mov-video-converter' },
        { name: 'WMV Video Converter', path: '/tools/video/wmv-video-converter' },
        { name: 'MKV Video Converter', path: '/tools/video/mkv-video-converter' },
        { name: 'WebM Video Converter', path: '/tools/video/webm-video-converter' },
        { name: 'FLV Video Converter', path: '/tools/video/flv-video-converter' },
        { name: 'Batch Video Converter', path: '/tools/video/batch-video-converter' },
        { name: 'Video Trimmer & Cutter', path: '/tools/video/video-trimmer-cutter' },
        { name: 'Video Merger', path: '/tools/video/video-merger' },
        { name: 'Video Splitter', path: '/tools/video/video-splitter' },
        { name: 'Video Rotator', path: '/tools/video/video-rotator' },
        { name: 'Video Resizer', path: '/tools/video/video-resizer' },
        { name: 'Video Speed Changer', path: '/tools/video/video-speed-changer' },
        { name: 'Video Stabilizer', path: '/tools/video/video-stabilizer' },
        { name: 'Video Color Corrector', path: '/tools/video/video-color-corrector' },
        { name: 'Video Compressor', path: '/tools/video/video-compressor' },
        { name: 'Video Quality Enhancer', path: '/tools/video/video-quality-enhancer' },
        { name: 'Video Optimizer for Web', path: '/tools/video/video-optimizer-for-web' },
        { name: 'Mobile Video Optimizer', path: '/tools/video/mobile-video-optimizer' },
        { name: 'Video Bitrate Calculator', path: '/tools/video/video-bitrate-calculator' },
        { name: 'Video Metadata Editor', path: '/tools/video/video-metadata-editor' },
        { name: 'Video Thumbnail Generator', path: '/tools/video/video-thumbnail-generator' },
        { name: 'Video Frame Extractor', path: '/tools/video/video-frame-extractor' },
        { name: 'Audio Extractor', path: '/tools/video/audio-extractor' },
        { name: 'Video to GIF Converter', path: '/tools/video/video-to-gif-converter' },
        { name: 'Subtitle Extractor', path: '/tools/video/subtitle-extractor' },
        { name: 'Video Info Analyzer', path: '/tools/video/video-info-analyzer' },
        { name: 'Video Repair Tool', path: '/tools/video/video-repair-tool' },
        { name: 'Screen Recorder', path: '/tools/video/screen-recorder' },
        { name: 'Webcam Recorder', path: '/tools/video/webcam-recorder' },
        { name: 'Video Downloader', path: '/tools/video/video-downloader' },
      ]
    },
    audio: {
      title: 'Audio Tools',
      tools: [
        { name: 'MP3 Audio Converter', path: '/tools/audio/MP3AudioConverter' },
        { name: 'WAV Audio Converter', path: '/tools/audio/WAVAudioConverter' },
        { name: 'AAC Audio Converter', path: '/tools/audio/AACAudioConverter' },
        { name: 'FLAC Audio Converter', path: '/tools/audio/FLACAudioConverter' },
        { name: 'OGG Audio Converter', path: '/tools/audio/OGGAudioConverter' },
        { name: 'M4A Audio Converter', path: '/tools/audio/M4AAudioConverter' },
        { name: 'WMA Audio Converter', path: '/tools/audio/WMAAudioConverter' },
        { name: 'Batch Audio Converter', path: '/tools/audio/BatchAudioConverter' },
        { name: 'Audio Trimmer & Cutter', path: '/tools/audio/AudioTrimmerCutter' },
        { name: 'Audio Merger', path: '/tools/audio/AudioMerger' },
        { name: 'Audio Splitter', path: '/tools/audio/AudioSplitter' },
        { name: 'Volume Adjuster', path: '/tools/audio/VolumeAdjuster' },
        { name: 'Audio Speed Changer', path: '/tools/audio/AudioSpeedChanger' },
        { name: 'Pitch Shifter', path: '/tools/audio/PitchShifter' },
        { name: 'Audio Reverb Tool', path: '/tools/audio/AudioReverbTool' },
        { name: 'Noise Reducer', path: '/tools/audio/NoiseReducer' },
        { name: 'Voice Recorder', path: '/tools/audio/VoiceRecorder' },
        { name: 'Screen Audio Recorder', path: '/tools/audio/ScreenAudioRecorder' },
        { name: 'Podcast Recorder', path: '/tools/audio/PodcastRecorder' },
        { name: 'Interview Recorder', path: '/tools/audio/InterviewRecorder' },
        { name: 'Music Recorder', path: '/tools/audio/MusicRecorder' },
        { name: 'Dictation Recorder', path: '/tools/audio/DictationRecorder' },
        { name: 'Meeting Recorder', path: '/tools/audio/MeetingRecorder' },
        { name: 'Radio Recorder', path: '/tools/audio/RadioRecorder' },
        { name: 'Audio Spectrum Analyzer', path: '/tools/audio/AudioSpectrumAnalyzer' },
        { name: 'Audio Waveform Viewer', path: '/tools/audio/AudioWaveformViewer' },
        { name: 'Audio Quality Analyzer', path: '/tools/audio/AudioQualityAnalyzer' },
        { name: 'Audio Metadata Editor', path: '/tools/audio/AudioMetadataEditor' },
        { name: 'Audio Bitrate Calculator', path: '/tools/audio/AudioBitrateCalculator' },
        { name: 'Silence Detector', path: '/tools/audio/SilenceDetector' },
        { name: 'Audio File Info', path: '/tools/audio/AudioFileInfo' },
        { name: 'Peak Level Meter', path: '/tools/audio/PeakLevelMeter' },
      ]
    },
    pdf: {
      title: 'PDF Tools',
      tools: [
        { name: 'PDF to Word Converter', path: '/tools/pdf/PDFtoWordConverter' },
        { name: 'PDF to Excel Converter', path: '/tools/pdf/PDFtoExcelConverter' },
        { name: 'PDF to PowerPoint Converter', path: '/tools/pdf/PDFtoPowerPointConverter' },
        { name: 'PDF to Images Converter', path: '/tools/pdf/PDFtoImagesConverter' },
        { name: 'Word to PDF Converter', path: '/tools/pdf/WordToPDFConverter' },
        { name: 'Excel to PDF Converter', path: '/tools/pdf/ExcelToPDFConverter' },
        { name: 'PowerPoint to PDF Converter', path: '/tools/pdf/PowerPointToPDFConverter' },
        { name: 'Images to PDF Converter', path: '/tools/pdf/ImagesToPDFConverter' },
        { name: 'PDF Text Editor', path: '/tools/pdf/PDFTextEditor' },
        { name: 'PDF Page Editor', path: '/tools/pdf/PDFPageEditor' },
        { name: 'PDF Annotation Tool', path: '/tools/pdf/PDFAnnotationTool' },
        { name: 'PDF Form Filler', path: '/tools/pdf/PDFFormFiller' },
        { name: 'PDF Watermark Tool', path: '/tools/pdf/PDFWatermarkTool' },
        { name: 'PDF Header Footer Tool', path: '/tools/pdf/PDFHeaderFooterTool' },
        { name: 'PDF Page Numbering', path: '/tools/pdf/PDFPageNumbering' },
        { name: 'PDF Background Tool', path: '/tools/pdf/PDFBackgroundTool' },
        { name: 'PDF Merger Tool', path: '/tools/pdf/PDFMergerTool' },
        { name: 'PDF Splitter Tool', path: '/tools/pdf/PDFSplitterTool' },
        { name: 'PDF Page Extractor', path: '/tools/pdf/PDFPageExtractor' },
        { name: 'PDF Organizer', path: '/tools/pdf/PDFOrganizer' },
        { name: 'PDF Bookmark Manager', path: '/tools/pdf/PDFBookmarkManager' },
        { name: 'PDF Batch Processor', path: '/tools/pdf/PDFBatchProcessor' },
        { name: 'PDF Size Reducer', path: '/tools/pdf/PDFSizeReducer' },
        { name: 'PDF Repair Tool', path: '/tools/pdf/PDFRepairTool' },
        { name: 'PDF Password Protector', path: '/tools/pdf/PDFPasswordProtector' },
        { name: 'PDF Unlocker', path: '/tools/pdf/PDFUnlocker' },
        { name: 'PDF Encryption Tool', path: '/tools/pdf/PDFEncryptionTool' },
        { name: 'PDF Permission Manager', path: '/tools/pdf/PDFPermissionManager' },
        { name: 'PDF Digital Signature', path: '/tools/pdf/PDFDigitalSignature' },
        { name: 'PDF Redaction Tool', path: '/tools/pdf/PDFRedactionTool' },
        { name: 'PDF Metadata Remover', path: '/tools/pdf/PDFMetadataRemover' },
        { name: 'PDF Security Analyzer', path: '/tools/pdf/PDFSecurityAnalyzer' },
      ]
    },
  };

  const category = toolCategories[activeCategory as keyof typeof toolCategories];

  if (!category) {
    return null;
  }

  // Calculate tools per column for better distribution
  const toolsPerColumn = Math.ceil(category.tools.length / 4);

  return (
    <div className="absolute left-0 w-full bg-white shadow-lg border-t z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">{category.title}</h3>
        <div className="grid grid-cols-4 gap-8">
          {Array.from({ length: 4 }, (_, columnIndex) => {
            const startIndex = columnIndex * toolsPerColumn;
            const endIndex = startIndex + toolsPerColumn;
            const columnTools = category.tools.slice(startIndex, endIndex);
            
            return (
              <div key={columnIndex} className="space-y-2">
                {columnTools.map((tool) => (
                  <Link
                    key={tool.name}
                    to={tool.path}
                    className="block text-sm text-gray-700 hover:text-blue-600 hover:bg-gray-50 px-2 py-1 rounded transition-colors"
                    onClick={onClose}
                  >
                    {tool.name}
                  </Link>
                ))}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default MegaMenu;
