// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyomxuzhutqmsonfxjez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5b214dXpodXRxbXNvbmZ4amV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIxMjIsImV4cCI6MjA2NTQ5ODEyMn0.S3qnxASmJPJYwZK2Rpy0uA29wDQa1K1yVBU7Y_T73dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);